# Generated by Django 4.2.5 on 2024-12-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_user_options_remove_user_game_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
