# Generated by Django 4.2.5 on 2024-12-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_user_correct_answers_user_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
    ]
