# Generated by Django 4.2.5 on 2024-12-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_user_highest_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
